# Generated by Django 4.2.7 on 2023-11-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVar',
            fields=[
                ('var_nm', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('var_val', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyStore',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pubkey', models.TextField()),
                ('prikey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestOtp',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('ipaddr', models.GenericIPAddressField()),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('mail_idx', models.PositiveSmallIntegerField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPwd',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pwd', models.TextField()),
                ('salt', models.BinaryField()),
                ('activate', models.BooleanField()),
                ('key_pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='otpass.keystore')),
            ],
        ),
    ]
