# Generated by Django 4.2.6 on 2023-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpwd',
            name='pwd',
            field=models.TextField(),
        ),
    ]
